export enum Currency {
  USD = "United States Dollar",
  EUR = "Euro",
  JPY = "Japanese Yen",
  GBP = "British Pound Sterling",
  AUD = "Australian Dollar",
  CAD = "Canadian Dollar",
  CHF = "Swiss Franc",
  CNY = "Chinese Yuan",
  SEK = "Swedish Krona",
  NZD = "New Zealand Dollar",
  KRW = "South Korean Won",
  SGD = "Singapore Dollar",
  NOK = "Norwegian Krone",
  MXN = "Mexican Peso",
  INR = "Indian Rupee",
  BRL = "Brazilian Real",
  RUB = "Russian Ruble",
  ZAR = "South African Rand",
  HKD = "Hong Kong Dollar",
  TRY = "Turkish Lira",
}
